[["Source.SUB650WYE-S2"]]
property = "OperatingVoltageA"
subscription = "psse.Buses.17605.PU"
multiplier = 2.4 

[["Source.SUB650WYE-S2"]]
property = "OperatingVoltageB"
subscription = "psse.Buses.17605.PU"
multiplier = 2.4 

[["Source.SUB650WYE-S2"]]
property = "OperatingVoltageC"
subscription = "psse.Buses.17605.PU"
multiplier = 2.4 