[["Source.SUB650WYE-S2"]]
property = "OperatingVoltageA"
subscription = "test.feederhead.voltageA"
multiplier = 1.0 

[["Source.SUB650WYE-S2"]]
property = "OperatingVoltageB"
subscription = "test.feederhead.voltageB"
multiplier = 1.0

[["Source.SUB650WYE-S2"]]
property = "OperatingVoltageC"
subscription = "test.feederhead.voltageC"
multiplier = 1.0 