[["Source.DEMO-STATION-S1"]]
property = "OperatingVoltageA"
subscription = "test.feederhead.voltageA"
multiplier = 1

[["Source.DEMO-STATION-S1"]]
property = "OperatingVoltageB"
subscription = "test.feederhead.voltageB"
multiplier = 1

[["Source.DEMO-STATION-S1"]]
property = "OperatingVoltageC"
subscription = "test.feederhead.voltageC"
multiplier = 1