["InductionMotor"]
"regex filter" = "\\b\\d\\d.\\d"
"properties" = ["kW"]

["Transformer"]
"regex filter" = "\\b\\d\\d.\\d"
"properties" = ["IA", "IB", "IC"]

["DistributedLoad"]
"regex filter" = "\\b\\d-\\d"
"properties" = ["IA", "IB", "IC"]

["Source"]
"regex filter" = ""
"properties" = ["KWTOT", "KVARTOT", "OperatingVoltageA"]