[project]
start_time = "2017-1-1 00:00:00.0"
end_time = "2017-1-2 00:00:00.0"
time_step_min = 1
max_iter = 50
error_tolerance = 0.001
simulation_type = "QSTS"
project_path = "C:\\Users\\alatif\\Desktop\\CYMEPY\\examples\\Example1"
mdb_file = "Feeder1_2.mdb"
sxst_file = "Feeder1_2.sxst"
cyme_installation_directory = "C:\\Program Files (x86)\\CYME\\CYME"

[helics]
cosimulation_mode = true
coiter_mode = false
coiter_error_tolerance = 0.1
max_coiter = 20
broker = "127.0.0.1"
broker_port = 50001
federate_name = "CYME"
time_delta = 0.01
core_type = "ZMQ"
uninterruptible = true
helics_logging_level = 5

[logger]
logging_level = "DEBUG"
log_to_external_file = true
display_on_screen = true
clear_old_log_file = true
pre_configured_logging = false

[profiles]
use_profiles = true
use_internal_profile_manager = true
source_type = "h5"
source = "EnergyProfiles.mdb"
is_relavtive_path = true