[Project]
"Start Year" = 2017
"Start Day" = 1
"Start Time (min)" = 0.0
"End Day" = 1
"End Time (min)" = 31.0
"Step resolution (min)" = 1
"Max Control Iterations" = 50
"Error tolerance" = 0.001
"Control mode" = "Static"
"Simulation Type" = "QSTS"
"Project Path" = "C:\\Users\\alatif\\Desktop\\CYMEPY\\examples"
"Active Project" = "Example1"
"MDB File" = "Feeder1_2.mdb"
"SXST File" = "Feeder1_2.sxst"
"Cyme Installation Directory" = "C:\\Program Files\\CYME\\CYME"

[Helics]
"Co-simulation Mode" = true
"Iterative Mode" = false
"Error tolerance" = 0.1
"Max co-iterations" = 20
"Broker" = "mainbroker"
"Broker port" = 50001
"Federate name" = "PyDSS"
"Time delta" = 0.01
"Core type" = "zmq"
Uninterruptible = true
"Helics logging level" = 5

["Logger options"]
"Logging Level" = "DEBUG"
"Log to external file" = true
"Display on screen" = true
"Clear old log file" = true
"Pre-configured logging" = false

["Profile settings"]
"Use profiles" = true
"Use internal profile manager" = false
"profile database" = "EnergyProfiles.mdb"
